---
- name: restart jupyter
  systemd:
    name: "{{ jupyter_service_name }}"
    user: yes
    state: restarted
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  become: yes
...
