---
- name: add azure signing key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
  register: apt_key_result
  until: apt_key_result.msg |d('') is not search('timed out')

- name: add azure repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ lin_apt_arch }}] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_lsb.codename }} main"
    filename: azure-cli
    mode: 0644

- name: install azure cli
  ansible.builtin.apt:
    name: azure-cli
    state: "{{ devhost_upgrade |bool |ternary('latest','present') }}"
...
