---
- name: install beam, the solusvm client
  ansible.builtin.pip:
    name: beam
    executable: pip3

- name: configure solusvm vps machines for beam
  ansible.builtin.template:
    src: beam.ini.j2
    dest: ~/.beam.ini
    mode: 0640
  become: false
...
