---
# handlers for ivansible.dev_nomad

- name: restart consul service
  ansible.builtin.systemd:
    name: consul
    state: restarted
    enabled: true
  become: true

- name: restart nomad service
  ansible.builtin.systemd:
    name: nomad
    state: restarted
    enabled: true
  become: true
...
