---
- name: refresh facts as non-root
  setup:
  become: no

- block:
    - name: install packer binary
      import_tasks: install.yml
      become: yes
      tags: dev_packer_install

    - name: create directory for packer plugins
      file:
        state: directory
        path: "{{ packer_plugin_dir }}"

    - name: install 3rd-party packer plugins
      import_tasks: plugins.yml
      tags: dev_packer_plugins

    - name: configure permitted users for packer
      import_tasks: user.yml
      when: "'permitted' in group_names"
  tags:
  - dev_packer
  - ip4only
...
