---
# install 3rd-party packer plugins

# see:
#   https://github.com/AnchorFree/packer-builder-vultr/blob/master/bintray.md
- name: download plugin packer-builder-vultr
  unarchive:
    remote_src: yes
    src: https://dl.bintray.com/content/askholme/packer-vultr/packer-builder-vultr_{{ packer_builder_vultr_version }}_linux_amd64.tar.gz
    dest: "{{ packer_plugin_dir }}"
    exclude: README.md
    extra_opts: --strip-components=1
    creates: "{{ packer_allow_reinstall | ternary(omit, packer_plugin_dir + '/packer-builder-vultr') }}"
...
