---
# install 3rd-party packer plugins

# see:
#   https://github.com/AnchorFree/packer-builder-vultr/blob/master/bintray.md
- name: download plugin packer-builder-vultr
  unarchive:
    remote_src: true
    src: "{{ url_releases }}/v{{ packer_builder_vultr_version }}/packer-builder-vultr_v{{ packer_builder_vultr_version }}_linux_amd64.zip"
    dest: "{{ packer_plugin_dir }}"
    exclude:
      - LICENSE
      - README.md
    creates: "{{ packer_allow_reinstall_plugins | ternary(omit, packer_plugin_dir + '/packer-builder-vultr') }}"
    # perform operations as root - workaround for unarchive issue in docker
    # see https://github.com/ansible/ansible/issues/49284
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid |string }}"
    mode: 0755
  become: true
  # temporary variables to reduce length of lines
  vars:
    url_releases: https://github.com/ivandeex/packer-builder-vultr/releases/download
  # fix intermittent network failures
  register: download_result
  until: "'timed out' not in download_result.msg |default('')"
...
