---
# install 3rd-party packer plugins

# see:
#   https://github.com/AnchorFree/packer-builder-vultr/blob/master/bintray.md
- name: download plugin packer-builder-vultr
  unarchive:
    remote_src: yes
    src: https://github.com/ivandeex/packer-builder-vultr/releases/download/v{{ packer_builder_vultr_version }}/packer-builder-vultr_v{{ packer_builder_vultr_version }}_linux_amd64.zip
    dest: "{{ packer_plugin_dir }}"
    exclude:
      - LICENSE
      - README.md
    creates: "{{ packer_allow_reinstall_plugins | ternary(omit, packer_plugin_dir + '/packer-builder-vultr') }}"
  # fix intermittent network failures
  register: download_result
  until: "'timed out' not in download_result.msg |default('')"
...
