---
# install 3rd-party packer plugins

# see:
#   https://github.com/AnchorFree/packer-builder-vultr/blob/master/bintray.md
- name: download plugin packer-builder-vultr
  get_url:
    url: "https://github.com/ivandeex/packer-builder-vultr/releases/download/{{ packer_builder_vultr_version }}/packer-builder-vultr_linux_amd64"
    dest: "{{ packer_plugin_dir }}/packer-builder-vultr"
    mode: 0755
    force: "{{ packer_allow_reinstall_plugins }}"
...
