---
namespace: ivansible
name: devel
version: 1.0.0

description: Ansible collection for development tools

authors:
  - Ivan Andreev <ivandeex@gmail.com>

tags:
  # max. 20 tags
  - linux
  - tools
  - go
  - digitalocean
  - hetzner
  - vultr
  - github
  - aws
  - azure
  - heroku
  - jupyter
  - codeserver
  - hashicorp
  - consul
  - nomad
  - terraform
  - vagrant
  - virtualbox

# https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification
# namespace.name: version_range
dependencies: {}

repository: https://github.com/ivansible/devel
documentation: https://github.com/ivansible/devel
homepage: https://github.com/ivansible/devel
issues: https://github.com/ivansible/devel/issues

readme: README.md
license: MIT

build_ignore:
  - '*.pyc'
  - '*.tar'
...
