---
- name: custom git configuration
  ansible.builtin.template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 0640
    force: "{{ dev_user_git_force |bool }}"
  register: result_new_gitconfig

- name: example git configuration
  ansible.builtin.template:
    src: gitconfig.j2
    dest: ~/.gitconfig.example
    mode: 0640
    force: "{{ dev_user_git_force |bool }}"
  register: result_gitconfig_example

- name: warn about new gitconfig
  ansible.builtin.debug:
    msg:
      - "Wrote new git configuration in ~/.gitconfig"
  when: result_new_gitconfig is changed
     or result_gitconfig_example is changed

- name: netrc file for git (optional)
  no_log: "{{ hide_secrets |bool }}"
  ansible.builtin.lineinfile:
    path: ~/.netrc
    line: "machine {{ item.host }} login {{ item.user }} password {{ item.pass }}"
    create: true
    mode: 0600
  loop: "{{ dev_user_netrc }}"
...
