---
- name: install user utils (oath tool, pssh, etc)
  apt:
    name: oathtool,pssh
  become: true
  tags:
    - dev_user_utils
    - dev_user_all

- name: bashrc customizations
  import_tasks: bashrc.yml
  tags:
    - dev_user_bashrc
    - dev_user_all

- name: git config customizations
  import_tasks: git-config.yml
  when: is_permitted |bool
  tags:
    - dev_user_gitconfig
    - dev_user_git
    - dev_user_all


- name: customize tmux
  import_tasks: tmux.yml
  tags:
    - dev_user_utils
    - dev_user_tmux
    - dev_user_all


- name: authorize public keys
  import_tasks: ssh-authorize.yml
  tags:
    - dev_user_ssh_all
    - dev_user_all
    - dev_user_ssh_keys

- name: generate ssh config
  import_tasks: ssh-config.yml
  tags:
    - dev_user_ssh_all
    - dev_user_ssh_config
    - dev_user_all

- name: install ssh keys
  import_tasks: ssh-keys.yml
  tags:
    - dev_user_ssh_all
    - dev_user_ssh_keys
    - dev_user_all


- name: directory for user binaries
  file:
    path: ~/bin
    state: directory
    mode: 0755
  tags:
    - dev_user_utils
    - dev_user_all


- name: install backup-restore scripts on target host
  import_role:
    name: ivansible.base.backup
    tasks_from: install_scripts.yml
  become: true
  tags:
    - dev_user_utils
    - dev_user_all
...
