---
- name: generate rsa ssh key for user, if not yet exists
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: true
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_comment: "{{ ansible_user_id }}@{{ inventory_hostname }} ansible-generated"

- name: example ssh config
  template:
    src: ssh.config.j2
    dest: ~/.ssh/config
    mode: 0600
    force: "{{ dev_user_ssh_config_override |bool }}"

- name: reverse ssh config entry
  block:
    - name: derive host name and port of reverse connection
      set_fact:
        revssh_name: "{{ dev_user_rev_ssh_host }}"
        revssh_host: "{{ hostvars[dev_user_rev_ssh_host]['ansible_host'] }}"
        revssh_port: "{{ hostvars[dev_user_rev_ssh_host]['ansible_port'] }}"

    - name: insert reverse ssh entry in ssh config
      blockinfile:
        path: ~/.ssh/config
        create: true
        mode: 0600
        block: |
          Host {{ revssh_name }}
            Hostname {{ revssh_host }}
            Port {{ revssh_port }}
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            LogLevel ERROR
        marker: "# == {mark} reverse ssh =="
        insertafter: "^#\\."

    - name: warn about reverse config entry
      debug:
        msg:
          - "Create reverse forwarding: ssh -R {{ revssh_port }}:{{ revssh_host }}:{{ ansible_port }} -p{{ ansible_port }} {{ ansible_fqdn }}"
          - "Get back via reverse port: ansible revssh -m ping"
  when:
    - dev_user_rev_ssh_host in hostvars
    - is_permitted |bool


- name: insert example entry in ssh config
  blockinfile:
    path: ~/.ssh/config
    create: true
    mode: 0600
    block: |
      Host {{ inventory_hostname }}.example
        Hostname {{ example_fqdn |d(inventory_hostname, true) }}
        Port {{ real_ssh_port |d(ansible_port) |d(22) }}
        User {{ ansible_user_id }}
        StrictHostKeyChecking no
        IdentityFile ~/.ssh/{{ primary_key |d('id_rsa', true) }}
    marker: "# == {mark} example entry =="
    insertafter: "^#\\."
  vars:
    primary_key: "{{ dev_user_ssh_keys_deploy |d([''], true) |first |basename }}"
    ## On github runners the ansible_fqdn value sometimes includes
    ## a domain like `.internal.cloudapp.net` but sometimes doesn't,
    ## resulting in sporadic idempotence failures.
    ## As a workaround, we force a fixed domain here.
    example_fqdn: "{{ fixed_fqdn if fixed_domain else fact_fqdn }}"
    fixed_fqdn: "{{ fact_fqdn |regex_replace('^([^.]+).*$', '\\1.'+fixed_domain) }}"
    fixed_domain: "{{ dev_user_example_domain |d('',true) }}"
    fact_fqdn: "{{ ansible_fqdn |d('',true) }}"
  when: is_permitted |bool
...
