---
- name: tmux bash completion (optional)
  get_url:
    url: https://raw.githubusercontent.com/imomaliev/tmux-bash-completion/master/completions/tmux
    dest: /etc/bash_completion.d/tmux
    force: "{{ dev_user_force_settings |bool }}"
    mode: 0644
  become: true
  failed_when: false
  ## get_url always reports as changed in check mode
  when: not ansible_check_mode

- name: tmux bashrc snippets
  blockinfile:
    path: ~/.local/bashrc/3common.sh
    block: "{{ lookup('file', 'bashrc/tmux.sh') }}"
    marker: "# == {mark} TMUX FUNCTIONS =="
    insertafter: EOF
    create: true
    mode: 0644

- name: customize tmux
  lineinfile:
    path: ~/.tmux.conf
    line: "{{ item }}"
    create: true
    mode: 0644
  loop: "{{ dev_user_tmux_settings }}"

- name: customize top
  copy:
    src: top.rc
    dest: ~/.toprc
    mode: 0644
    force: "{{ dev_user_force_settings |bool }}"
...
