alias c='clear'
alias g='git'
alias gnp='git --no-pager'
alias h='head'
alias l='ls --color=auto --group-directories-first'
alias md='mkdir'
alias m='less -XCS'
alias pg='ps -efa | grep -i'
alias rmf='/bin/rm -f'
alias rmrf='/bin/rm -rf'
alias t='tail'
alias tf='tail -F'
alias v='vim'
alias wl='wc -l'

alias jc='sudo journalctl'
alias sc='sudo systemctl'
alias scr='sudo systemctl daemon-reload'
alias scu='systemctl --user'

alias tma='tmux attach'
alias tt='tmux attach'
alias sus='sudo -Hs'

alias dr='docker'
alias dc='docker-compose'
alias dm='docker-machine'
alias vg='vagrant'

alias anp='ansible-playbook'
alias ang='ansible-galaxy'
alias angii='ansible-galaxy import ivansible'
alias vact='. .venv/bin/activate'
