---
- name: create standalone directory for collections
  file:
    state: directory
    path: "{{ divan_collections_dir }}"
    mode: 0755

- name: create symbolic link for collections in ivantory
  file:
    state: link
    src: "{{ collections_relink }}"
    dest: "{{ collections_subdir }}"
  vars:
    collections_subdir: "{{ divan_dir }}/collections/ansible_collections"
    collections_parent: "{{ collections_subdir |dirname }}"
    collections_relink: "{{ divan_collections_dir |realpath |relpath(collections_parent) }}"
  tags: divan_links

- name: create standalone directory for galaxy roles
  file:
    state: directory
    path: "{{ divan_roles_dir }}"
    mode: 0755

- name: create symbolic link for galaxy roles in ivantory
  file:
    state: link
    src: "{{ roles_relink }}"
    dest: "{{ roles_subdir }}"
  vars:
    roles_subdir: "{{ divan_dir }}/roles"
    roles_parent: "{{ roles_subdir |dirname }}"
    roles_relink: "{{ divan_roles_dir |realpath |relpath(roles_parent) }}"
  tags: divan_links

- name: configure galaxy token
  copy:
    dest: "{{ ansible_user_dir }}/.ansible/galaxy_token"
    content: "token: {{ divan_galaxy_token }}\n"
    force: true
    mode: 0600
  when:
    - divan_galaxy_token |d('')

- name: install galaxy roles
  # old pre-2.9 syntax: ansible-galaxy install
  # new 2.9+ syntax is: ansible-galaxy role install
  command: >
    "{{ divan_venv_dir }}/bin/ansible-galaxy"
        role install
        "--role-file={{ divan_roles_list_file }}"
        "--roles-path={{ divan_roles_dir }}"
        --no-deps
        --keep-scm-meta
        --force
  args:
    chdir: "{{ divan_dir }}"
    creates: "{{ divan_roles_dir }}/{{ divan_roles_check_role }}"
  when:
    - divan_roles_list_file |d('')
    - divan_roles_check_role |d('')
    - divan_galaxy_token |d('')

- name: assert that probe galaxy role was installed
  file:
    path: "{{ divan_roles_dir }}/{{ divan_roles_check_role }}/meta/main.yml"
    state: file
  when:
    - divan_roles_list_file |d('')
    - divan_roles_check_role |d('')
    - divan_galaxy_token |d('')
...
