---
- name: setup user for development
  ansible.builtin.include_role:
    name: ivansible.devel.user
    apply:
      tags: divan_prepare_user
  vars:
    ## please enable dev_user_install_keys in inventory for permitted group
    # dev_user_install_keys: true
    dev_user_setup_system: true
  when: not divan_skip_prepare |bool
  tags:
    - divan_prepare_user
    - divan_prepare
    - divan_all

- name: install user-local ansible
  ansible.builtin.include_role:
    name: ivansible.devel.ansible
    apply:
      tags: divan_prepare_user
  vars:
    dev_ansible_dir: "{{ divan_venv_dir }}"
  when: not divan_skip_prepare |bool
  tags:
    - divan_prepare_ansible
    - divan_prepare
    - divan_all

- name: install github cli
  ansible.builtin.import_tasks: hub.yml
  become: true
  when: git_hub_release |d('')
  tags:
    - divan_install_hub
    - divan_all
    - ip4only

- name: checkout inventory and playbooks
  ansible.builtin.git:
    dest: "{{ divan_dir }}"
    repo: "{{ divan_repo }}"
    version: "{{ divan_branch }}"
    ## only clone, don't choke on pending modifications
    update: false
    accept_hostkey: true
  register: checkout_result
  ## retry on sporadic network failures
  until: checkout_result.stderr |d('') is not search('timed out')
  when: is_permitted |bool
  tags:
    - divan_checkout
    - divan_all

- name: configure inventory git for push upstream
  community.general.git_config:
    repo: "{{ divan_dir }}"
    scope: local
    name: push.default
    value: upstream
  when: is_permitted |bool
  tags:
    - divan_checkout
    - divan_all

- name: symbolic links for ivantory
  ansible.builtin.import_tasks: links.yml
  tags:
    - divan_links
    - divan_all

## note: ansible requirements are already installed by ivansible.dev_ansible

- name: decrypt repository
  ansible.builtin.import_tasks: crypt.yml
  when:
    - is_permitted |bool
    - divan_sops_age_recipients |d('')
  tags:
    - divan_decrypt
    - divan_all

- name: install required collections and roles
  ansible.builtin.import_tasks: collections.yml
  when: is_permitted |bool
  tags:
    - divan_collections
    - divan_all

- name: set ssh for insecure developer login to vagrant boxes
  ## See: http://hakunin.com/six-ansible-practices
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.ssh/config"
    create: true
    mode: 0600
    block: |
      Host vagrant-box
        Hostname vagrant-box.dev
        Port {{ real_ssh_port | d(ansible_port) | d(22) }}
      {# Never complain about ever-changing host keys #}
        StrictHostKeyChecking no
      {# Never try to remember those keys via known_hosts #}
        UserKnownHostsFile /dev/null
      {# Never report about making such awful things #}
        LogLevel ERROR
    marker: '# {mark} vagrant box example'
  tags:
    - divan_ssh_config
    - divan_all
...
