---
- name: detect latest packer release
  ivansible.base.github_release:
    repository: hashicorp/packer
    release: "{{ packer_version }}"
    strip_v: true
    template: https://releases.hashicorp.com/packer/{ver}/packer_{ver}_linux_amd64.zip
    creates: "{{ packer_binary }}"
    reinstall: "{{ packer_upgrade |bool }}"
  register: _packer_release

- name: download archived packer binary
  unarchive:
    remote_src: true
    src: "{{ _packer_release.url }}"
    dest: "{{ packer_binary |dirname }}"
  when: _packer_release is changed
  ## fix intermittent network failures
  register: _packer_download
  until: _packer_download.msg |default('') is not search('timed out')
...
