---
- block:
    - name: install packer binary
      import_tasks: install.yml
      become: true
      tags: dev_packer_install

    - name: create directory for packer plugins
      file:
        state: directory
        path: "{{ packer_plugin_dir }}"
        mode: 0755

    - name: install 3rd-party packer plugins
      import_tasks: plugins.yml
      tags: dev_packer_plugins

    - name: configure permitted users for packer
      import_tasks: user.yml
      when: is_permitted |bool
  tags:
    - dev_packer_all
    - ip4only
...
