---
# this must be a subdirectory of user home directory
jupyter_work_subdir: jupyter

# leave blank to skip checkout of a repository
jupyter_git_repos: []

# leave blank when password is not set
jupyter_password: ""

# leave blank to skip integration with nginx
jupyter_nginx_hostname: ""

# certificate and private key for ssl
jupyter_nginx_ssl_cert: ""
jupyter_nginx_ssl_pkey: ""

# this port will be open if nginx is not configured
jupyter_port: 8888

jupyter_root_dir: "{{ ansible_user_dir }}/.jupyter"

jupyter_work_dir: "{{ ansible_user_dir }}/{{ jupyter_work_subdir }}"

jupyter_password_salt: deadbeef2018

jupyter_service_name: jupyter

jupyter_service_unit: "{{ ansible_user_dir }}/.config/systemd/user/{{ jupyter_service_name }}.service"

jupyter_system_packages:
  - python3
  - python3-dev
  - virtualenv
  - build-essential
  - cmake
  - graphviz
  - xauth
  - imagemagick
  - libpq-dev

jupyter_pip_stage1:
  - certifi
  - chardet
  - cvxopt
  - cython
  - django
  - flask
  - graphviz
  - ipython
  - jupyter
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - matplotlib
  - networkx
  - numba
  - numdifftools
  - numpy
  - openpyxl
  - pandas
  - pillow
  - psycopg2
  - pydot
  - pydotplus
  - pymongo
  - python-dateutil
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - scrapy
  - seaborn
  - sphinx
  - sqlalchemy
  - statsmodels
  - sympy
  - xlrd
  - xlsxwriter
  - jupyterthemes
  - bs4

jupyter_pip_stage2:
  - cvxpy

jupyter_pip_extras: []

jupyter_theme: ""
...
