---
# defaults for dev-user

is_permitted: false

dev_user_git_fullname: "{{ ansible_user_id }}"
dev_user_git_email: "{{ ansible_user_id + '@' + (ansible_fqdn | default(inventory_hostname, true)) }}"

dev_user_install_keys: false
dev_user_require_keys: true

# by default, all keys are authorized, but only the first one is installed
dev_user_authorized_keys_files: "{{ lin_ssh_keys_files }}"
dev_user_installed_keys_files: "{{ dev_user_authorized_keys_files[0:1] }}"

dev_user_authorized_git_repos:
  - github.com
  - gitlab.com
dev_user_git_repo_key: ""

dev_user_known_host_list: "{{ dev_user_authorized_git_repos }}"

dev_user_group_vars: {}
dev_user_host_vars: {}
dev_user_extra_vars: {}

dev_user_all_vars: "{{ dev_user_group_vars
                     | combine(dev_user_host_vars)
                     | combine(dev_user_extra_vars) }}"

dev_user_group_secrets: {}
dev_user_host_secrets: {}
dev_user_extra_secrets: {}

dev_user_all_secrets: "{{ dev_user_group_secrets
                        | combine(dev_user_host_secrets)
                        | combine(dev_user_extra_secrets) }}"

dev_user_netrc: []
# - host: hostname
#   user: username
#   pass: password

dev_user_rev_ssh_host: revssh
...
