---
# defaults file for dev-user

dev_user_git_fullname: "{{ ansible_user_id }}"
dev_user_git_email: "{{ ansible_user_id + '@' + (ansible_fqdn | default(inventory_hostname, true)) }}"

dev_user_install_keys: true
dev_user_require_keys: true
dev_user_keys_files: "{{ query('fileglob', 'files/secret/vanko-*.key') }}"

dev_user_rev_ssh_host: revssh

dev_user_setup_system: true

dev_user_system_packages:
  - gzip
  - unzip
  - unrar
  - git
  - build-essential

dev_user_known_host_list:
  - github.com
  - gitlab.com


ngrok_zip_url: latest

git_hub_release: latest
git_hub_archive_url: "https://github.com/github/hub/releases/download/v{{ git_hub_release }}/hub-linux-amd64-{{ git_hub_release }}.tgz"
git_hub_dir: "/usr/local/hub/{{ git_hub_archive_url | basename | splitext | first }}"
git_hub_remake_links: false
git_hub_man_dir: /usr/local/share/man/man1
git_hub_completion_dir: /etc/bash_completion.d

...
