---
# tasks file for ivansible.dev_vagrant

- setup:

- name: vagrant from ppa (not recommended)
  apt:
    name: vagrant
  become: yes
  when: vagrant_package_url == 'ppa'
  register: vagrant_ppa_result
  tags: dev_vagrant

- import_tasks: vagrant.yml
  become: yes
  when: vagrant_package_url != 'ppa'
  tags: dev_vagrant

- import_tasks: plugins.yml
  become: no
  when: vagrant_plugin_list | length > 0
  tags: dev_vagplugins

- name: authenticate with vagrant cloud
  command:
    argv:
      - vagrant
      - login
      - -t
      - "{{ vagrant_cloud_token }}"
    creates: ~/.vagrant.d/data/vagrant_login_token
  become: no
  when: vagrant_cloud_token != ''
  tags: dev_vaglogin
...
