---
- name: vagrant from ppa (not recommended)
  apt:
    name: vagrant
  become: true
  when: vagrant_package_url == 'ppa'
  register: vagrant_ppa_result
  tags:
    - dev_vaginstall
    - dev_vagrant

- import_tasks: vagrant.yml
  become: true
  when: vagrant_package_url != 'ppa'
  tags:
    - dev_vaginstall
    - dev_vagrant

- import_tasks: plugins.yml
  become: false
  when: vagrant_plugin_list |length > 0
  tags:
    - dev_vagplugins
    - dev_vagrant

- name: checkout vagrant files, if permitted
  git:
    dest: "{{ vagrant_files_dir }}"
    repo: "{{ vagrant_files_repo }}"
    version: "{{ vagrant_files_branch }}"
    # only clone, don't choke on pending modifications
    update: false
    accept_hostkey: true
  when:
    - vagrant_files_repo |default('')  # noqa 602
    - is_permitted |bool               # noqa 602
  tags:
    - dev_vagrantfiles
    - dev_vagrant

- name: authenticate with vagrant cloud (optional, so ok to fail)
  # use transient environment variable to hide token from command line
  shell: vagrant cloud auth login -t $_vagrant_cloud_token
  args:
    creates: ~/.vagrant.d/data/vagrant_login_token
  environment:
    _vagrant_cloud_token: "{{ vagrant_cloud_token }}"
  become: false
  ignore_errors: true
  when:
    - is_permitted |bool
    - vagrant_use_login |bool
    - vagrant_cloud_token |default('')  # noqa 602
  tags:
    - dev_vaglogin
    - dev_vagrant
...
