---
- name: setup consul as root
  ansible.builtin.import_tasks: consul.yml
  when: consul_enable |bool
  become: true
  tags:
    - dev_consul_all

- name: setup nomad as root
  ansible.builtin.import_tasks: nomad.yml
  when: nomad_enable |bool
  become: true
  tags:
    - dev_nomad_all

- name: restart services
  ansible.builtin.meta: flush_handlers
  tags:
    - dev_consul_all
    - dev_nomad_all
...
