---
- name: custom git configuration
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 0640
    force: no
  register: result_new_gitconfig

- name: example git configuration
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig.example
    mode: 0640
  register: result_gitconfig_example

- name: warn about new gitconfig
  debug:
    msg:
      - "Wrote new git configuration in ~/.gitconfig"
  when: result_new_gitconfig is changed
        or result_gitconfig_example is changed
...
