---
- name: record public keys of known hosts
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    mode: 0640
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item + ' 2>/dev/null') }}"
    regexp: "{{ '^' + item }}"
  with_items: "{{ dev_user_known_host_list }}"
...
