---
- name: enable public keys of known hosts
  known_hosts:
    path: "{{ key_file }}"
    name: "{{ key_name }}"
    # fall back to locally cached host keys if ssh keyscan fails
    key: "{{ lookup('pipe', keyscan_cmd) or lookup('pipe', fallback_cmd) }}"
  vars:
    key_file: /etc/ssh/ssh_known_hosts
    key_type: rsa
    keyscan_cmd: "ssh-keyscan -t {{ key_type }} -p {{ ssh_port }} {{ hostname }} 2>/dev/null"
    fallback_cmd: "grep -F '{{ key_name }}' '{{ key_file }}' ||true |grep ssh-{{ key_type }} |head -1"
    # key_name: host -> host, host:port -> [host]:port
    key_name: "{{ hostname if ssh_port == '22' else '[%s]:%s' % (hostname, ssh_port) }}"
    # ssh_port: host -> 22, host:port -> port
    ssh_port: "{{ (item + ':22') |regex_search(':[0-9]+') |regex_replace(':') }}"
    # hostname: strip port from item
    hostname: "{{ item |regex_replace(':.*') }}"
  # retry sporadic ssh-keyscan failures on vagrant
  register: ssh_keyscan_result
  until: ssh_keyscan_result is successful
  loop: "{{ dev_user_known_host_list }}"
  tags: dev_user_known_hosts
...
