---
- name: bashrc customizations
  import_tasks: bashrc.yml
  tags: dev_user_bashrc

- name: git config customizations
  import_tasks: git-config.yml
  tags: dev_user_gitconfig

- name: ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: install ssh keys
  block:
    - name: verify the keys to copy
      assert:
        that: "dev_user_keys_files | length > 0"
        msg: "access keys not found!"
      when: "dev_user_require_keys | bool == true"

    - name: copy ssh keys
      copy:
        src: "{{ item }}"
        dest: ~/.ssh/
        mode: 0400
      loop: "{{ dev_user_keys_files }}"
  when: "'workspace' in group_names and dev_user_install_keys | bool == true"
  tags: dev_user_install_keys

- name: generate ssh config
  import_tasks: ssh-config.yml
  tags: dev_user_ssh_config

- name: directory for user binaries
  file:
    path: ~/bin/
    state: directory

- name: install gendiff utility
  copy:
    src: gendiff
    dest: ~/bin/
    mode: 0755
    force: no

- import_tasks: system.yml
  become: yes
  when: "dev_user_setup_system | bool == true"
  tags: dev_user_setup_system
...
