---
- name: install oath tool
  apt:
    name: oathtool
  become: true
  tags:
    - dev_user_utils
    - dev_user_all

- name: bashrc customizations
  import_tasks: bashrc.yml
  tags:
    - dev_user_bashrc
    - dev_user_all

- name: git config customizations
  import_tasks: git-config.yml
  when: is_permitted |bool
  tags:
    - dev_user_gitconfig
    - dev_user_all


- name: customize tmux
  import_tasks: tmux.yml
  tags:
    - dev_user_utils
    - dev_user_tmux
    - dev_user_all


- name: authorize public keys
  import_tasks: ssh-authorize.yml
  tags:
    - dev_user_ssh_all
    - dev_user_all
    - dev_user_ssh_keys

- name: generate ssh config
  import_tasks: ssh-config.yml
  tags:
    - dev_user_ssh_all
    - dev_user_ssh_config
    - dev_user_all

- name: install ssh keys
  import_tasks: ssh-keys.yml
  when: dev_user_install_keys |bool
  tags:
    - dev_user_ssh_all
    - dev_user_ssh_keys
    - dev_user_all


- name: directory for user binaries
  file:
    path: ~/bin
    state: directory
  tags:
    - dev_user_utils
    - dev_user_all


- name: install backup-restore scripts on target host
  import_role:
    name: ivansible.backup_base
    tasks_from: install_scripts.yml
  become: true
  tags:
    - dev_user_utils
    - dev_user_all
...
