---
- name: bashrc customizations
  import_tasks: bashrc.yml
  tags:
    - dev_user_bashrc

- name: git config customizations
  import_tasks: git-config.yml
  when: is_permitted |bool
  tags:
    - dev_user_gitconfig


- name: customize tmux
  lineinfile:
    path: ~/.tmux.conf
    line: "{{ item }}"
    create: yes
  loop:
    - "set-option -g history-limit 22000"
    - "bind -n C-k clear-history"  # clear scroll buffer on ^K
    - "new-session"                # auto-create new sessions
  tags:
    - dev_user_utils
    - dev_user_tmux


- name: ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
    mode: 0700
  tags:
    - dev_user_ssh_all


- name: fix local keys permissions for ssh-keygen
  file:
    path: "{{ item }}"
    mode: 0600
  loop: "{{ dev_user_authorized_keys_files }}"
  loop_control:
    label: "{{ item | basename }}"
  # connection:local fails when target is docker
  # https://willthames.github.io/2018/07/01/connection-local-vs-delegate_to-localhost.html
  delegate_to: localhost
  tags:
    - dev_user_ssh_all
    - dev_user_ssh_pubkeys

- name: authorize public keys
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ lookup('pipe', 'ssh-keygen -y -f \"{{ item }}\"') }}"
    comment: "{{ item | basename | regex_replace('[.]key$') }}"
    state: present
  when: item != '' # noqa 602
  loop: "{{ dev_user_authorized_keys_files }}"
  loop_control:
    label: "{{ item | basename }}"
  tags:
    - dev_user_ssh_all
    - dev_user_ssh_pubkeys

- name: generate ssh config
  import_tasks: ssh-config.yml
  tags:
    - dev_user_ssh_all
    - dev_user_ssh_config

- name: install ssh keys
  import_tasks: ssh-keys.yml
  when: dev_user_install_keys |bool
  tags:
    - dev_user_ssh_all
    - dev_user_install_keys

- name: enable public keys of known hosts
  import_tasks: known-hosts.yml
  become: yes
  when: dev_user_install_keys |bool and is_permitted |bool
  tags:
    - dev_user_ssh_all
    - dev_user_known_hosts


- name: directory for user binaries
  file:
    path: ~/bin/
    state: directory
  tags:
    - dev_user_utils

- name: install gendiff utility
  copy:
    src: gendiff
    dest: ~/bin/
    mode: 0755
    force: no
  tags:
    - dev_user_utils

- import_tasks: system.yml
  become: yes
  when: dev_user_setup_system |bool
  tags:
    - dev_user_setup_system

- import_tasks: go.yml
  when: dev_user_go_version != '' # noqa 602
  become: yes
  tags:
    - dev_user_utils
    - dev_user_go

- import_tasks: ngrok.yml
  when: dev_user_extras |bool
  become: yes
  tags:
    - dev_user_install_ngrok
    - ip4only

- import_tasks: hub.yml
  when: dev_user_extras |bool
  become: yes
  tags:
    - dev_user_install_hub
    - ip4only

- name: install backup-restore scripts on target host
  import_role:
    name: ivansible.backup_base
    tasks_from: install_scripts.yml
  become: yes
  tags:
    - dev_user_install_backup
...
