---
- name: bashrc customizations
  import_tasks: bashrc.yml
  tags:
    - dev_user_bashrc
    - dev_user_all

- name: git config customizations
  import_tasks: git-config.yml
  when: is_permitted |bool
  tags:
    - dev_user_gitconfig
    - dev_user_all


- name: customize tmux
  lineinfile:
    path: ~/.tmux.conf
    line: "{{ item }}"
    create: true
  loop:
    - "set-option -g history-limit 22000"
    - "bind -n C-k clear-history"  # clear scroll buffer on ^K
    - "new-session"                # auto-create new sessions
  tags:
    - dev_user_utils
    - dev_user_tmux
    - dev_user_all


- name: ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
    mode: 0700
  tags:
    - dev_user_ssh_all
    - dev_user_all


- name: fix local keys permissions for ssh-keygen
  file:
    path: "{{ item }}"
    mode: 0600
  loop: "{{ dev_user_authorized_keys_files }}"
  loop_control:
    label: "{{ item | basename }}"
  # connection:local fails when target is docker
  # https://willthames.github.io/2018/07/01/connection-local-vs-delegate_to-localhost.html
  delegate_to: localhost
  tags:
    - dev_user_ssh_all
    - dev_user_ssh_pubkeys
    - dev_user_all

- name: authorize public keys
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ lookup('pipe', 'ssh-keygen -y -f \"{{ item }}\"') }}"
    comment: "{{ item | basename | regex_replace('[.]key$') }}"
    state: present
  when: item != '' # noqa 602
  loop: "{{ dev_user_authorized_keys_files }}"
  loop_control:
    label: "{{ item | basename }}"
  tags:
    - dev_user_ssh_all
    - dev_user_ssh_pubkeys
    - dev_user_all

- name: generate ssh config
  import_tasks: ssh-config.yml
  tags:
    - dev_user_ssh_all
    - dev_user_ssh_config
    - dev_user_all

- name: install ssh keys
  import_tasks: ssh-keys.yml
  when: dev_user_install_keys |bool
  tags:
    - dev_user_ssh_all
    - dev_user_install_keys
    - dev_user_all


- name: directory for user binaries
  file:
    path: ~/bin
    state: directory
  tags:
    - dev_user_utils
    - dev_user_all


- name: install backup-restore scripts on target host
  import_role:
    name: ivansible.backup_base
    tasks_from: install_scripts.yml
  become: true
  tags:
    - dev_user_install_backup
    - dev_user_all
...
