---
- name: detect ngrok download location
  uri:
    url: https://ngrok.com/download
    return_content: true
    creates: /usr/local/bin/ngrok
  #connection: local  # never use delegation with "creates"
  register: ngrok_download_html
  # ngrok.com sporadically fails
  until: (ngrok_download_html.msg |default('') |regex_search('timed out')) is none
  when: ngrok_zip_url == 'latest'

- name: extract ngrok download location
  set_fact:
    ngrok_zip_url:
      "{{ ngrok_download_html.content
        | regex_search('https://[^\"]+ngrok-stable-linux-amd64.zip') }}"
  when: "'content' in ngrok_download_html"

- name: install ngrok
  unarchive:
    remote_src: true
    src: "{{ ngrok_zip_url }}"
    dest: /usr/local/bin
    creates: /usr/local/bin/ngrok
...
