---
## apply patches to ansible, mitogen and molecule

- name: detect site-packages directory
  ansible.builtin.shell:
    cmd: |
      from __future__ import print_function
      import sys
      [print(dir) for dir in sys.path if dir.endswith('site-packages')]
    executable: "{{ dev_ansible_dir }}/bin/python"
  changed_when: false
  register: detect_site_packages_result

- name: create symbolic link for site-packages
  ansible.builtin.file:
    state: link
    src: "{{ site_packages |relpath(venv_dir) }}"
    dest: "{{ venv_dir }}/site-packages"
  vars:
    site_packages: "{{ detect_site_packages_result.stdout_lines |first }}"
    venv_dir: "{{ dev_ansible_dir |expanduser }}"

- name: patch molecule-docker to fix async issues with mitogen
  ## mitogen speeds up main plays greatly, but create/destroy plays from
  ## molecule-docker use async wait which get stuck with mitogen, so patch
  ## https://github.com/mitogen-hq/mitogen/issues/835#issuecomment-978127345
  ansible.posix.patch:
    src: docker-mitogen.patch
    basedir: "{{ dev_ansible_dir }}/site-packages/molecule_docker"
    strip: 1
    backup: true
  failed_when: false

- name: patch mitogen for bug with distro 1.7.0
  ## https://github.com/mitogen-hq/mitogen/issues/906#issuecomment-1079173163
  ansible.posix.patch:
    src: mitogen-distro.patch
    basedir: "{{ dev_ansible_dir }}/site-packages/mitogen"
    strip: 1
    backup: true
  failed_when: false

- name: patch ansible-mitogen to wrap community.docker.docker connections
  ansible.posix.patch:
    src: mitogen-docker.patch
    basedir: "{{ dev_ansible_dir }}/site-packages/ansible_mitogen"
    strip: 1
    backup: true
  failed_when: false

- name: patch mitogen to fix pending work still existed after shutdown
  ansible.posix.patch:
    src: mitogen-shutdown.patch
    dest: "{{ dev_ansible_dir }}/site-packages/mitogen/core.py"
    backup: true
  failed_when: false
...
