---
dependencies:
  - ivansible.lin_base  # for lin_ssh_keys_files

galaxy_info:
  role_name: dev_user
  author: "Ivan Andreev"
  description: "Configure common bash aliases for remote user"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - developer
    - bash
...
