alias c='clear'
alias dfh='df -h .'
alias g='git'
alias gn='git --no-pager'
alias gg='grep'
alias h='head'
alias l='ls --color=auto --group-directories-first'
alias md='mkdir -p'
alias m='sudo less -XCR'
alias mm='sudo less -XCSR'
alias pg='ps -efa | grep -i'
alias rmf='/bin/rm -rf'
alias ssht='ssh -qt'
alias t='tail'
alias ttf='tail -F'
alias trr='sudo traceroute'
alias v='vim'
alias wl='wc -l'

alias sd='sudo'
alias sus='sudo -Hs'
alias ssu='sudo su -'
alias tt='tmux attach-session'
alias ttsave='tmux capture-pane -p -S- -E- > tmux.out'
alias ttclear='tmux clear-history'

alias sc='sudo systemctl'
alias scs='sudo systemctl stop'
alias sct='sudo systemctl status'
alias scr='sudo systemctl restart'
alias scl='sudo systemctl reload'
alias sce='sudo systemctl enable --now'
alias scd='sudo systemctl disable --now'
alias scdr='sudo systemctl daemon-reload'
alias scu='systemctl --user'
alias jc='sudo journalctl'
alias jcu='sudo journalctl -u'

alias kc='kubectl'
alias vg='vagrant'
alias ygc='sudo yggdrasilctl'
alias rc='rclone'

alias anp='ansible-playbook'
alias ang='ansible-galaxy'
alias angii='ansible-galaxy role import ivansible'
alias vact='. .venv/bin/activate'
