---
# defaults for ivansible.dev_packer

packer_version: latest
packer_allow_reinstall: no
packer_linux_binary: /usr/local/bin/packer

packer_plugin_dir: ~/.packer.d/plugins
packer_builder_vultr_version: "0.1"

packer_templates_repo: ""
packer_templates_branch: master
packer_templates_dir: ~/devel/packer
...
