---
- name: verify
  hosts: all
  tasks:
    - name: check go version on host
      command: go version
      when: ansible_connection != 'docker'
      register: go_ver_host

    - name: check go version in docker
      # options '-i -l' force interactive login shell
      command: bash -i -l -c 'go version'
      when: ansible_connection == 'docker'
      register: go_ver_docker

    - assert:  # noqa 502
        that: go_ver_host.stdout |default(go_ver_docker.stdout) |regex_search('go version go[12]\.')
...
