---
- name: create directory for galaxy roles
  file:
    state: directory
    path: "{{ divan_roles_dir }}"

- name: create symbolic link for galaxy roles
  file:
    state: link
    src: "{{ divan_roles_dir |relpath(divan_dir) }}"
    dest: "{{ divan_dir }}/roles-galaxy"
  tags: divan_links

- name: install galaxy roles
  command: >
    "{{ divan_venv_dir }}/bin/ansible-galaxy"
        install
        "--role-file={{ divan_roles_list_file }}"
        "--roles-path={{ divan_roles_dir }}"
        --no-deps
        --keep-scm-meta
        --force
  args:
    chdir: "{{ divan_dir }}"
    creates: "{{ divan_roles_dir }}/{{ divan_roles_check_role }}"
  when: divan_roles_list_file and divan_roles_check_role

- name: check that non-empty galaxy_login file exists
  stat:
    path: "{{ ansible_user_dir }}/.ansible_galaxy"
  register: dot_galaxy
  changed_when: not dot_galaxy.stat.exists or dot_galaxy.stat.size == 0
  when: divan_github_token != '' # noqa 602

- name: perform galaxy login using github token
  command: >
    "{{ divan_venv_dir }}/bin/ansible-galaxy"
        login
        "--github-token={{ divan_github_token }}"
  when: divan_github_token and dot_galaxy is changed
...
