---
- name: detect latest github cli release
  github_release:
    repository: github/hub
    release: "{{ git_hub_release }}"
    strip_v: true
    version_script: "{{ git_hub_binary }} --version |grep 'hub version'"
    script_regex: "[0-9.]+"
    template: "{download_url}/hub-linux-amd64-{ver}.tgz"
  register: latest_hub_release

- name: record github cli release
  set_fact:
    git_hub_release: "{{ latest_hub_release.release }}"

- name: create parent directory for github cli
  file:
    path: "{{ git_hub_dir |dirname }}"
    state: directory

- name: download and unpack github cli archive
  unarchive:
    remote_src: true
    src: "{{ latest_hub_release.url }}"
    dest: "{{ git_hub_dir |dirname }}"
    creates: "{{ git_hub_dir }}"
  register: unpack_hub_archive

- name: link to github cli binary
  file:
    src: "{{ git_hub_dir }}/bin/hub"
    dest: "{{ git_hub_binary }}"
    state: link
    force: true

- name: directory for github cli man pages
  file:
    dest: "{{ git_hub_man_dir }}"
    state: directory

- name: links for github cli man pages
  shell: >
    for page in *.1 ; do
      ln -sf \
        "{{ (git_hub_dir + '/share/man/man1')
          | relpath(git_hub_man_dir) }}/$page" \
        "{{ git_hub_man_dir }}/"
    done
  args:
    chdir: "{{ git_hub_dir }}/share/man/man1"
  when: unpack_hub_archive is not skipped
        or git_hub_remake_links |bool

- name: bash completion for github cli
  file:
    src: "{{ git_hub_dir }}/etc/hub.bash_completion.sh"
    dest: "{{ git_hub_completion_dir }}/hub"
    state: link
...
