---
# tasks file for dev-ivantory

- include_role:
    name: ivansible.dev_user
    apply:
      tags: divan_prepare_user
  vars:
    # please enable dev_user_install_keys in inventory for permitted group
    #dev_user_install_keys: true
    dev_user_setup_system: true
  when: not divan_skip_prepare |bool
  tags: divan_prepare_user

- include_role:
    name: ivansible.dev_ansible
    apply:
      tags: divan_prepare_user
  vars:
    dev_ansible_dir: "{{ divan_venv_dir }}"
  when: not divan_skip_prepare |bool
  tags: divan_prepare_ansible


- name: checkout inventory and playbooks
  git:
    dest: "{{ divan_dir }}"
    repo: "{{ divan_repo }}"
    version: "{{ divan_branch }}"
    update: no  # only clone, don't choke on pending modifications
    accept_hostkey: yes
  tags: divan_checkout


- name: decrypt repository
  import_tasks: transcrypt.yml
  when: "divan_password != ''"
  tags: divan_decrypt


- name: install galaxy roles
  command: >
    "{{ divan_venv_dir }}/bin/ansible-galaxy"
        install
        --role-file="{{ divan_dir | expanduser }}/{{ divan_roles_list_file }}"
        --roles-path="{{ divan_dir | expanduser }}/{{ divan_roles_subdir }}"
        --no-deps
        --keep-scm-meta
        --force
  args:
    chdir: "{{ divan_dir }}"
    creates: "{{ divan_dir }}/{{ divan_roles_subdir }}/{{ divan_roles_check_role }}"
  when: "divan_roles_list_file != ''
         and divan_roles_check_role != ''"
  tags: divan_galaxy

- name: check that non-empty galaxy_login file exists
  stat:
    path: "{{ ansible_user_dir }}/.ansible_galaxy"
  register: dot_ansible_galaxy
  tags: divan_galaxy

- name: perform galaxy login using github token
  command: >
    "{{ divan_venv_dir }}/bin/ansible-galaxy"
        login
        --github-token "{{ divan_github_token }}"
  when: "divan_github_token != ''
         and (not dot_ansible_galaxy.stat.exists
              or dot_ansible_galaxy.stat.size == 0)"
  tags: divan_galaxy


- name: template of insecure developer login to vagrant boxes
  # See: http://hakunin.com/six-ansible-practices
  blockinfile:
    path: "{{ ansible_user_dir }}/.ssh/config"
    create: yes
    mode: 0600
    block: |
      Host vagrant-box
        Hostname vagrant-box.dev
        Port {{ ansible_port }}
      {# Never complain about ever-changing host keys #}
        StrictHostKeyChecking no
      {# Never try to remember those keys via known_hosts #}
        UserKnownHostsFile /dev/null
      {# Never report about making such awful things #}
        LogLevel ERROR
    marker: '# {mark} vagrant box example'
  tags: divan_ssh_config
...
