---
# tasks file for dev-ivansible

- import_role:
    name: ivansible.dev-user
  vars:
    dev_user_install_keys: true
    dev_user_setup_system: true
  tags: dev_ivansible_prepare_user


- name: checkout inventory and playbooks
  git:
    dest: "{{ dev_ivansible_dir }}"
    repo: "{{ dev_ivansible_repo }}"
    version: "{{ dev_ivansible_branch }}"
    update: no  # only clone, don't choke on pending modifications
    accept_hostkey: yes


- name: install transcrypt
  get_url:
    url: "{{ dev_ivansible_transcrypt_url }}"
    dest: /usr/local/bin/transcrypt
    mode: 0755
    force: "{{ dev_ivansible_transcrypt_reinstall }}"
  become: yes

- name: decrypt repository
  block:
    - name: enable rekeying
      file:
        path: "{{ dev_ivansible_encrypted_flag }}"
        state: absent
      when: "dev_ivansible_rekey | bool == true"

    - name: decypher repository
      command: >
        /usr/local/bin/transcrypt
          -c "{{ dev_ivansible_cipher }}"
          -p "{{ dev_ivansible_password }}"
          -y
      args:
        chdir: "{{ dev_ivansible_dir }}"
        creates: "{{ dev_ivansible_encrypted_flag }}"
      register: transcrypt_result
      failed_when:
        transcrypt_result.rc != 0 and 'repository is already configured' not in transcrypt_result.stderr

    - name: mark repository as encrypted
      file:
        path: "{{ dev_ivansible_encrypted_flag }}"
        state: touch
      when: "transcrypt_result is successful"
      changed_when: false
  when: "dev_ivansible_password != ''"
  tags: dev_ivansible_decrypt


- name: harden file permissions in secret directories
  block:
    - name: find secret files
      command: transcrypt --list
      args:
        chdir: "{{ dev_ivansible_dir }}"
      changed_when: false
      failed_when: false
      register: transcrypt_list

    - set_fact:
        secret_repo_files: "{{ transcrypt_list.stdout_lines
                             | map('regex_replace', '^', dev_ivansible_dir + '/')
                             | list }}"

    - name: harden file permissions
      file:
        path: "{{ item }}"
        mode: 0600
      with_items: "{{ secret_repo_files }}"
  tags: dev_ivansible_harden_secrets


- name: install system packages
  apt:
    name: "{{ dev_ivansible_system_packages }}"
  become: true

- name: setup virtual environment
  pip:
    requirements: "{{ dev_ivansible_dir }}/requirements.txt"
    virtualenv: "{{ dev_ivansible_dir }}/.venv"
    virtualenv_python: "{{ dev_ivansible_python }}"


- name: template of insecure developer login to vagrant boxes
  # See: http://hakunin.com/six-ansible-practices
  blockinfile:
    dest: .ssh/config
    create: yes
    mode: 0600
    block: |
      Host vagrant-box
        Hostname vagrant-box.dev
        Port {{ ansible_port }}
      {# Never complain about ever-changing host keys #}
        StrictHostKeyChecking no
      {# Never try to remember those keys via known_hosts #}
        UserKnownHostsFile /dev/null
      {# Never report about making such awful things #}
        LogLevel ERROR
    marker: '# {mark} vagrant box example'
  tags: dev_ivansible_ssh_config
...
