---
# tasks file for dev-ivantory

- include_role:
    name: ivansible.dev_user
    apply:
      tags: divan_prepare_user
  vars:
    # please enable dev_user_install_keys in inventory for permitted group
    #dev_user_install_keys: true
    dev_user_setup_system: true
  when: not divan_skip_prepare |bool
  tags:
  - divan_prepare_user
  - divan_prepare

- include_role:
    name: ivansible.dev_ansible
    apply:
      tags: divan_prepare_user
  vars:
    dev_ansible_dir: "{{ divan_venv_dir }}"
  when: not divan_skip_prepare |bool
  tags:
  - divan_prepare_ansible
  - divan_prepare

- name: checkout inventory and playbooks
  git:
    dest: "{{ divan_dir }}"
    repo: "{{ divan_repo }}"
    version: "{{ divan_branch }}"
    update: no  # only clone, don't choke on pending modifications
    accept_hostkey: yes
  register: checkout_result
  # github sporadically fails from .ru
  until: "'timed out' not in checkout_result.stderr |default('')"
  when: is_permitted |bool
  tags: divan_checkout

- name: create symbolic link for virtualenv
  file:
    state: link
    src: "{{ divan_venv_dir |relpath(divan_dir) }}"
    dest: "{{ divan_venv_link }}"
  tags: divan_links

- name: create symbolic link for requirements
  file:
    state: link
    src: "{{ divan_requirements_file |relpath(divan_requirements_link |dirname) }}"
    dest: "{{ divan_requirements_link }}"
  tags: divan_links

# note: ansible requirements are already installed by ivansible.dev_ansible

- name: decrypt repository
  import_tasks: crypt.yml
  when: divan_password and is_permitted |bool
  tags: divan_decrypt

- name: setup galaxy roles
  import_tasks: galaxy.yml
  when: is_permitted |bool
  tags: divan_galaxy

- name: template of insecure developer login to vagrant boxes
  # See: http://hakunin.com/six-ansible-practices
  blockinfile:
    path: "{{ ansible_user_dir }}/.ssh/config"
    create: yes
    mode: 0600
    block: |
      Host vagrant-box
        Hostname vagrant-box.dev
        Port {{ real_ssh_port | default(ansible_port) }}
      {# Never complain about ever-changing host keys #}
        StrictHostKeyChecking no
      {# Never try to remember those keys via known_hosts #}
        UserKnownHostsFile /dev/null
      {# Never report about making such awful things #}
        LogLevel ERROR
    marker: '# {mark} vagrant box example'
  tags: divan_ssh_config
...
