---
- name: install transcrypt
  get_url:
    url: "{{ dev_ivansible_transcrypt_url }}"
    dest: "{{ dev_ivansible_transcrypt_executable }}"
    mode: 0755
    force: "{{ dev_ivansible_transcrypt_reinstall | bool }}"
  become: yes


- name: decypher repository
  command: >
    "{{ dev_ivansible_transcrypt_executable }}"
      -c "{{ dev_ivansible_cipher }}"
      -p "{{ dev_ivansible_password }}"
      -y
  args:
    chdir: "{{ dev_ivansible_dir }}"
    creates: "{{ dev_ivansible_decrypted_flag }}"
  register: transcrypt_result
  failed_when:
    transcrypt_result.rc != 0 and 'repository is already configured' not in transcrypt_result.stderr

- name: mark repository as decrypted
  file:
    path: "{{ dev_ivansible_decrypted_flag }}"
    state: touch
  when: "transcrypt_result is successful"
  changed_when: false


- name: verify decryption
  block:
    - name: read content of the check file
      slurp:
        src: "{{ dev_ivansible_dir }}/{{ dev_ivansible_check_file }}"
      register: slurped_check_file

    - set_fact:
        check_file_content: "{{ (slurped_check_file['content'] | b64decode).strip() }}"
        check_file_basename: "{{ dev_ivansible_check_file | basename }}"

    - name: verify content of the check file
      assert:
        that: "check_file_content == check_file_basename"
  rescue:
    - name: remove failed checkout
      file:
        path: "{{ dev_ivansible_dir }}"
        state: absent

    - fail:
        msg: "Decryption failed! Maybe password is wrong? Aborting."
  when: dev_ivansible_check_file != ""
  tags: dev_ivansible_check_file


- name: harden permissions of secret files (slow way)
  block:
    - name: find secret files
      command: transcrypt --list
      args:
        chdir: "{{ dev_ivansible_dir }}"
      changed_when: false
      failed_when: false
      register: transcrypt_list

    - set_fact:
        secret_repo_files: "{{ transcrypt_list.stdout_lines
                             | map('regex_replace', '^', dev_ivansible_dir + '/')
                             | list }}"

    - name: harden permissions (slow way)
      file:
        path: "{{ item }}"
        mode: 0600
      loop: "{{ secret_repo_files }}"
  when: "dev_ivansible_harden_quickway | bool == false"
  tags: dev_ivansible_harden_secrets

- name: harden permissions (quick way)
  shell: transcrypt --list | xargs -r chmod 600
  args:
    chdir: "{{ dev_ivansible_dir }}"
  changed_when: false
  when: "dev_ivansible_harden_quickway | bool == true"
  tags: dev_ivansible_harden_secrets
...
