---
all:
  children:
    molecule:
      children:
        docker_molecule:
          vars:
            ansible_user: ansible
        local_molecule:
      vars:
        is_permitted: true  # permit installing the ivantory-test repo
        allow_sysctl: false
        lin_use_ssh: false
        lin_firewall: none
        lin_core_time_sync: false
        lin_core_system_locale: en_US.UTF-8

        divan_repo: https://github.com/ivansible/ivantory-test.git
        divan_dir: "{{ ansible_user_dir }}/test/ivantory"
        divan_collections_dir: "{{ ansible_user_dir }}/test/ansible_collections"
        divan_roles_dir: "{{ ansible_user_dir }}/test/galaxy"

        divan_sops_probe_file: files/check-file
        divan_sops_probe_text: "test passphrase"
...
