---
all:
  children:
    molecule:
      children:
        docker_molecule:
          vars:
            ansible_user: ansible
            lin_use_ssh: true   # to have user ssh keys tested in docker
        local_molecule:
          vars:
            lin_use_ssh: false  # no mucking with local ssh
      vars:
        is_permitted: false
        allow_sysctl: false
        lin_firewall: none
        lin_core_time_sync: false
        lin_core_system_locale: en_US.UTF-8
...
