---
- name: detect latest terraform release
  github_release:
    repository: hashicorp/terraform
    release: "{{ terraform_version }}"
    strip_v: true
    template: https://releases.hashicorp.com/terraform/{ver}/terraform_{ver}_linux_amd64.zip
    creates: "{{ terraform_binary }}"
    reinstall: "{{ terraform_upgrade |bool }}"
  register: _terraform_release

- name: download archived terraform binary
  unarchive:
    remote_src: true
    src: "{{ _terraform_release.url }}"
    dest: "{{ terraform_binary |dirname }}"
  when: _terraform_release is changed
  ## fix intermittent network failures
  register: _terraform_download
  until: _terraform_download.msg |default('') is not search('timed out')
...
