---
- name: detect latest terraform release
  github_release:
    repository: hashicorp/terraform
    release: "{{ terraform_version }}"
    strip_v: true
    template: https://releases.hashicorp.com/terraform/{ver}/terraform_{ver}_linux_amd64.zip
    creates: "{{ terraform_linux_binary }}"
    reinstall: "{{ terraform_allow_reinstall_terraform |bool }}"
  register: latest_terraform_release

- name: download archived terraform binary
  unarchive:
    remote_src: true
    src: "{{ latest_terraform_release.url }}"
    dest: "{{ terraform_linux_binary |dirname }}"
  when: latest_terraform_release is changed
  # fix intermittent network failures
  register: download_result
  until: "'timed out' not in download_result.msg |default('')"
...
