---
# configure permitted users for terraform

- name: configure terraform aliases (optional)
  lineinfile:
    path: ~/.local/bashrc/4alias.sh
    line: "alias {{ item }}"
  # skip this step if ivansible.dev_user wasn't installed
  ignore_errors: true
  loop:
    - "tf='terraform'"
    - "tfup='terraform apply -auto-approve'"
    - "tfdown='terraform destroy -auto-approve'"
    - "tfls='terraform state list'"
  tags: dev_terraform_aliases

- name: bash completion for terraform
  block:
    - name: user-local completion for terraform (will install globally if it fails)
      lineinfile:
        path: ~/.local/bashrc/5completion.sh
        line: "complete -C {{ terraform_binary }} terraform"
      become: false
  rescue:
    # fall back if ivansible.dev_user wasn't installed
    - name: system-global bash completion for terraform
      copy:
        dest: /etc/profile.d/completion_terraform.sh
        content: |
          # bash completion for HashiCorp Terraform
          # ansible-managed
          if [ -n "${BASH_VERSION-}" -a -n "${PS1-}" -a -n "${BASH_COMPLETION_VERSINFO-}" ]; then
              complete -C {{ terraform_binary }} terraform
          fi
      become: true
  tags: dev_terraform_completion


- name: checkout terraform plans, if permitted
  git:
    dest: "{{ terraform_plans_dir }}"
    repo: "{{ terraform_plans_repo }}"
    version: "{{ terraform_plans_branch }}"
    # only clone, don't choke on pending modifications
    update: false
    accept_hostkey: true
  when: terraform_plans_repo != '' and 'permitted' in group_names  # noqa 602
  tags: dev_terraform_plans

- name: setup terraform enterprise (free) token, if permitted
  blockinfile:
    path: ~/.terraformrc
    create: true
    mode: 0600
    block: |
      credentials "app.terraform.io" {
        token = "{{ terraform_api_token }}"
      }
      plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"
      disable_checkpoint = true
    marker: "# == {mark} terraform enterprise (free) =="
  when: terraform_api_token != '' and is_permitted |bool  # noqa 602
  tags: dev_terraform_api_token
...
